server:
    port: 8080
spring:
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/jcala_blog?useUnicode:true&amp;characterEncoding:UTF-8
        driverClassName: com.mysql.jdbc.Driver
        schema: classpath:import.sql
        data: classpath:data.sql
        initialize: false
        sql-script-encoding: UTF-8
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 50
            minimum-idle: 5
#mybatis:
#    type-aliases-package: me.jcala.blog.domain,me.jcala.blog.mapping
#    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
#    config-location: classpath:mybatis-config.xml
